with-expecter: True
dir: "mocks/{{ .PackageName }}"
mockname: "Mock{{ .InterfaceName }}"
outpkg: "{{ .PackageName }}mocks"
filename: "{{ .InterfaceName | snakecase }}.go"
recursive: true
packages:
  github.com/trancong12102/sish-gitlab-keys/internal:
    config:
      all: True
