// Code generated by mockery v2.43.2. DO NOT EDIT.

package main

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPHandler is an autogenerated mock type for the HTTPHandler type
type MockHTTPHandler struct {
	mock.Mock
}

type MockHTTPHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPHandler) EXPECT() *MockHTTPHandler_Expecter {
	return &MockHTTPHandler_Expecter{mock: &_m.Mock}
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *MockHTTPHandler) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// MockHTTPHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockHTTPHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *MockHTTPHandler_Expecter) ServeHTTP(_a0 interface{}, _a1 interface{}) *MockHTTPHandler_ServeHTTP_Call {
	return &MockHTTPHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", _a0, _a1)}
}

func (_c *MockHTTPHandler_ServeHTTP_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *MockHTTPHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockHTTPHandler_ServeHTTP_Call) Return() *MockHTTPHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPHandler_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockHTTPHandler_ServeHTTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPHandler creates a new instance of MockHTTPHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPHandler {
	mock := &MockHTTPHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
