// Code generated by mockery v2.43.2. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthorizer is an autogenerated mock type for the Authorizer type
type MockAuthorizer struct {
	mock.Mock
}

type MockAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizer) EXPECT() *MockAuthorizer_Expecter {
	return &MockAuthorizer_Expecter{mock: &_m.Mock}
}

// AuthorizePubKey provides a mock function with given fields: ctx, key
func (_m *MockAuthorizer) AuthorizePubKey(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizePubKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorizer_AuthorizePubKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizePubKey'
type MockAuthorizer_AuthorizePubKey_Call struct {
	*mock.Call
}

// AuthorizePubKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAuthorizer_Expecter) AuthorizePubKey(ctx interface{}, key interface{}) *MockAuthorizer_AuthorizePubKey_Call {
	return &MockAuthorizer_AuthorizePubKey_Call{Call: _e.mock.On("AuthorizePubKey", ctx, key)}
}

func (_c *MockAuthorizer_AuthorizePubKey_Call) Run(run func(ctx context.Context, key string)) *MockAuthorizer_AuthorizePubKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthorizer_AuthorizePubKey_Call) Return(_a0 error) *MockAuthorizer_AuthorizePubKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorizer_AuthorizePubKey_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthorizer_AuthorizePubKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorizer creates a new instance of MockAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizer {
	mock := &MockAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
