// Code generated by mockery v2.43.2. DO NOT EDIT.

package httpmocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockRouterHandler is an autogenerated mock type for the RouterHandler type
type MockRouterHandler struct {
	mock.Mock
}

type MockRouterHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouterHandler) EXPECT() *MockRouterHandler_Expecter {
	return &MockRouterHandler_Expecter{mock: &_m.Mock}
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *MockRouterHandler) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// MockRouterHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockRouterHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *MockRouterHandler_Expecter) ServeHTTP(_a0 interface{}, _a1 interface{}) *MockRouterHandler_ServeHTTP_Call {
	return &MockRouterHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", _a0, _a1)}
}

func (_c *MockRouterHandler_ServeHTTP_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *MockRouterHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockRouterHandler_ServeHTTP_Call) Return() *MockRouterHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouterHandler_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockRouterHandler_ServeHTTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRouterHandler creates a new instance of MockRouterHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouterHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouterHandler {
	mock := &MockRouterHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
