services:
  letsencrypt:
    image: adferrand/dnsrobocert:latest
    container_name: letsencrypt-dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/etc/letsencrypt
      - ./le-config.yml:/etc/dnsrobocert/config.yml
    restart: always
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    depends_on:
      - letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
      - ./config.yml:/app/config.yml
    command: --config /app/config.yml
    network_mode: host
    restart: always
  gitlab-keys-auth:
    image: trancong12102/sish-gitlab-keys:latest
    container_name: gitlab-keys-auth
    ports:
      - 8080:8080
    environment:
      - LISTEN_ADDR=:8080
      - GITLAB_URL=${GITLAB_URL}
      - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
    restart: always
