// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hellofresh/health-go/v5"
	"github.com/trancong12102/sish-gitlab-keys/internal/auth"
	"github.com/trancong12102/sish-gitlab-keys/internal/gitlab"
	"github.com/trancong12102/sish-gitlab-keys/internal/http"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeHTTPSrv(httpSrvConfig *http.ServerConfig, gitlabClientConfig *gitlab.ClientConfig, healthcheckOpts ...health.Option) (*http.Server, error) {
	client := gitlab.NewClient(gitlabClientConfig)
	service := auth.NewService(client)
	handler := auth.NewHandler(service)
	healthcheck, err := http.NewHealthcheck(healthcheckOpts...)
	if err != nil {
		return nil, err
	}
	router := http.NewRouter(handler, healthcheck)
	server := http.NewHTTPSrv(router, httpSrvConfig)
	return server, nil
}
